kind: pipeline
name: default

steps:
  - name: install
    image: elixir:1.9
    volumes:
      - name: mix
        path: /root/.mix
    commands:
      - mix local.rebar --force
      - mix local.hex --force
      - mix deps.get

  - name: test
    image: elixir:1.9
    volumes:
      - name: mix
        path: /root/.mix
    environment:
      DB_HOST: "database"
      MIX_ENV: "test"
    commands:
      - mix format --check-formatted
      - mix test

  - name: docker
    image: plugins/docker
    settings:
      username: podloveradiator
      password:
        from_secret: docker_password
      repo: podlove/frontman
      tags: latest
    when:
      branch:
        - master
      event:
        - push

services:
  - name: database
    image: postgres:9-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: frontman_test

volumes:
  - name: mix
    temp: {}
